version: "3.8"

services:

  backend:
    build:
      context: ./backend
    container_name: alertnest-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: alertnest-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
